name: Scala Package

on:
  release:
    types: [ created ]
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Publish package
        run: sbt "gin / Publish / publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIN_VERSION: ${{ github.ref_name }}
